import {
  CivicReport,
  AwsTelemetryEvent,
  StepFunctionExecution,
  CivicZone,
  PredictiveAlert,
  RootCauseInsight,
} from '@/types';

// Preset options for citizen rapid submission
export const PRESET_CIVIC_EVIDENCE = [
  {
    id: 'preset-pothole',
    title: 'Severe Asphalt Cavity & Sub-base Failure',
    category: 'road_damage' as const,
    defaultDescription: 'Dangerous 14-inch deep pothole near pedestrian crossing on Market St. Vehicles swerving into oncoming traffic to avoid rim damage.',
    address: '845 Market St, Sector 14, Civic Metro',
    lat: 37.7842,
    lng: -122.4075,
    imageUrl: 'https://images.unsplash.com/photo-1515162816999-a0c47dc192f7?auto=format&fit=crop&w=1000&q=80',
    severity: 'CRITICAL' as const,
    severityScore: 94,
    confidence: 97.2,
    department: 'Road Maintenance & Infrastructure',
    recommendedAction: 'Emergency cold-patch asphalt deployment and traffic safety cone perimeter within 2 hours.',
    detectedObjects: ['Asphalt Cavity', 'Exposed Sub-base', 'Traffic Hazard', 'Pedestrian Crossing Zone'],
    estimatedHours: 3.5,
  },
  {
    id: 'preset-drainage',
    title: 'Open Drainage & Collapsed Storm Culvert near School',
    category: 'public_hazard' as const,
    defaultDescription: 'Cast iron storm grate missing adjacent to elementary school crosswalk. Deep 6-foot vertical drop exposing children to fall danger.',
    address: '420 Campus Ave, Campus Gate, Civic Metro',
    lat: 37.7765,
    lng: -122.4185,
    imageUrl: 'https://images.unsplash.com/photo-1541888946425-d0fbb186156a?auto=format&fit=crop&w=1000&q=80',
    severity: 'CRITICAL' as const,
    severityScore: 96,
    confidence: 98.6,
    department: 'Public Utilities Commission (Drainage Division)',
    recommendedAction: 'Immediate barricade installation, steel trench plate cover, and rapid fabrication of replacement grate.',
    detectedObjects: ['Missing Manhole Grate', 'Uncovered Pit', 'School Zone Safety Hazard'],
    estimatedHours: 2.0,
  },
  {
    id: 'preset-streetlight',
    title: 'Exposed Live Wiring on Broken Streetlight Pole',
    category: 'streetlights' as const,
    defaultDescription: 'Municipal luminaire pole sheared at base with sparking 240V lines resting on wet sidewalk near public transit stop.',
    address: '1420 Mission St, Sector 14, Civic Metro',
    lat: 37.7735,
    lng: -122.4172,
    imageUrl: 'https://images.unsplash.com/photo-1509114397022-ed747cca3f65?auto=format&fit=crop&w=1000&q=80',
    severity: 'CRITICAL' as const,
    severityScore: 92,
    confidence: 98.4,
    department: 'Municipal Electrical & Power Bureau',
    recommendedAction: 'Immediate feeder circuit de-energization and high-voltage boom truck dispatch.',
    detectedObjects: ['Live Wiring', 'Deformed Aluminum Pole', 'Active Arc Flash Risk'],
    estimatedHours: 2.5,
  },
  {
    id: 'preset-garbage',
    title: 'Severe Waste Accumulation & Egress Blockage',
    category: 'garbage_overflow' as const,
    defaultDescription: 'Commercial dumpsters overflowing into pedestrian alley with rotting organics, biological waste, and broken glass blocking emergency exits.',
    address: '562 Howard St, Market Road, Civic Metro',
    lat: 37.7884,
    lng: -122.3989,
    imageUrl: 'https://images.unsplash.com/photo-1605600659873-d808a13e4d2a?auto=format&fit=crop&w=1000&q=80',
    severity: 'HIGH' as const,
    severityScore: 81,
    confidence: 93.8,
    department: 'Sanitation & Waste Management',
    recommendedAction: 'Heavy compactor truck dispatch, rodent baiting protocol, and sanitizing washdown.',
    detectedObjects: ['Uncontained Refuse', 'Biological Waste', 'Emergency Egress Obstruction'],
    estimatedHours: 4.0,
  },
];

// Civic Zones (Lightweight Digital Twin)
export const CIVIC_ZONES: CivicZone[] = [
  {
    id: 'zone-sec14',
    name: 'Sector 14',
    healthScore: 72,
    trendWeeklyPercent: -6,
    trendDirection: 'DOWN',
    activeReports: 47,
    criticalCount: 7,
    avgResolutionHours: 5.2,
    density: '18.4 reports/km²',
    topCategories: [
      { category: 'road_damage', count: 22, percentage: 46.8 },
      { category: 'streetlights', count: 14, percentage: 29.8 },
      { category: 'garbage_overflow', count: 11, percentage: 23.4 },
    ],
    recommendedIntervention: 'Deploy coordinated mobile asphalt patching and electrical survey crews along the main North Corridor.',
  },
  {
    id: 'zone-campus',
    name: 'Campus Gate',
    healthScore: 84,
    trendWeeklyPercent: 18,
    trendDirection: 'UP',
    activeReports: 29,
    criticalCount: 3,
    avgResolutionHours: 3.8,
    density: '12.1 reports/km²',
    topCategories: [
      { category: 'public_hazard', count: 12, percentage: 41.4 },
      { category: 'streetlights', count: 10, percentage: 34.5 },
      { category: 'road_damage', count: 7, percentage: 24.1 },
    ],
    recommendedIntervention: 'Conduct pedestrian infrastructure audit around school crossings prior to morning peak.',
  },
  {
    id: 'zone-market',
    name: 'Market Road',
    healthScore: 68,
    trendWeeklyPercent: -12,
    trendDirection: 'DOWN',
    activeReports: 21,
    criticalCount: 5,
    avgResolutionHours: 6.4,
    density: '24.7 reports/km²',
    topCategories: [
      { category: 'garbage_overflow', count: 11, percentage: 52.4 },
      { category: 'road_damage', count: 6, percentage: 28.6 },
      { category: 'water_leak', count: 4, percentage: 19.0 },
    ],
    recommendedIntervention: 'Increase municipal trash collection cycles from once daily to three times daily.',
  },
  {
    id: 'zone-industrial',
    name: 'Industrial Corridor',
    healthScore: 79,
    trendWeeklyPercent: 5,
    trendDirection: 'UP',
    activeReports: 18,
    criticalCount: 2,
    avgResolutionHours: 7.1,
    density: '6.8 reports/km²',
    topCategories: [
      { category: 'infrastructure', count: 8, percentage: 44.4 },
      { category: 'road_damage', count: 6, percentage: 33.3 },
      { category: 'water_leak', count: 4, percentage: 22.3 },
    ],
    recommendedIntervention: 'Heavy-freight axle weight enforcement to protect sub-base integrity.',
  },
  {
    id: 'zone-waterfront',
    name: 'Waterfront District',
    healthScore: 91,
    trendWeeklyPercent: -8,
    trendDirection: 'STABLE',
    activeReports: 14,
    criticalCount: 1,
    avgResolutionHours: 2.9,
    density: '8.5 reports/km²',
    topCategories: [
      { category: 'public_hazard', count: 6, percentage: 42.8 },
      { category: 'streetlights', count: 5, percentage: 35.7 },
      { category: 'water_leak', count: 3, percentage: 21.5 },
    ],
    recommendedIntervention: 'Routine preventive salt-mist corrosion checks on seaside lighting masts.',
  },
  {
    id: 'zone-oldtown',
    name: 'Old Town Heritage',
    healthScore: 86,
    trendWeeklyPercent: 2,
    trendDirection: 'STABLE',
    activeReports: 8,
    criticalCount: 0,
    avgResolutionHours: 4.5,
    density: '9.2 reports/km²',
    topCategories: [
      { category: 'infrastructure', count: 4, percentage: 50.0 },
      { category: 'public_hazard', count: 3, percentage: 37.5 },
      { category: 'garbage_overflow', count: 1, percentage: 12.5 },
    ],
    recommendedIntervention: 'Low-impact preservation repairs using historically certified masonry materials.',
  },
];

// Predictive Issue Alerts
export const PREDICTIVE_ALERTS: PredictiveAlert[] = [
  {
    id: 'alert-market-garbage',
    zoneName: 'Market Road',
    category: 'garbage_overflow',
    title: 'Surge in Commercial Refuse Spillover',
    percentageIncrease: 41,
    timeframe: 'over the last 7 days',
    recommendedAction: 'Schedule preventive sanitation inspection and increase nighttime compactor dispatch.',
    hasSufficientData: true,
    isSimulated: false,
  },
  {
    id: 'alert-sector14-pothole',
    zoneName: 'Sector 14',
    category: 'road_damage',
    title: 'Rainwater Sub-base Infiltration Cluster',
    percentageIncrease: 28,
    timeframe: 'following recent precipitation',
    recommendedAction: 'Deploy infrared thermal asphalt seal truck before micro-fractures propagate.',
    hasSufficientData: true,
    isSimulated: false,
  },
  {
    id: 'alert-campus-lighting',
    zoneName: 'Campus Gate',
    category: 'streetlights',
    title: 'Transformer Load Imbalance Warning',
    percentageIncrease: 18,
    timeframe: 'over the last 14 days',
    recommendedAction: 'Inspect substation breaker 4B; streetlight failures correlate with peak 8 PM load spike.',
    hasSufficientData: true,
    isSimulated: false,
  },
  {
    id: 'alert-oldtown-insufficient',
    zoneName: 'Old Town Heritage',
    category: 'infrastructure',
    title: 'Insufficient historical data for prediction',
    percentageIncrease: 0,
    timeframe: 'historical window < 30 days',
    recommendedAction: 'Continue baseline telemetry collection. Model requires minimum 15 reports for statistical significance.',
    hasSufficientData: false,
    isSimulated: false,
  },
];

// AI Root-Cause Insights (Systemic Analysis)
export const ROOT_CAUSE_INSIGHTS: RootCauseInsight[] = [
  {
    id: 'rc-light-feeder',
    title: 'Corridor-Wide Luminaire Outages traced to Feeder Cable',
    incidentCount: 23,
    primaryCategory: 'streetlights',
    corridor: 'Sector 14 — Mission St Transit Corridor (Blocks 12–28)',
    symptomFlow: [
      '23 citizen complaints logged',
      '14 individual streetlights reported dark',
      'Clustered along single 800m linear street corridor',
      'Bedrock topological correlation completed',
    ],
    hypothesis: 'Subterranean 3-phase neutral wire degradation caused by recent storm water ingress into Junction Vault 14-C. Individual bulb replacements will continuously fail.',
    recommendedAction: 'Inspect and replace the shared 3-phase feeder cable in Vault 14-C instead of treating bulbs separately.',
    systemicSavingsHours: 42.5,
  },
  {
    id: 'rc-water-pothole',
    title: 'Repetitive Asphalt Cavities caused by Underground Main Weeping',
    incidentCount: 16,
    primaryCategory: 'road_damage',
    corridor: 'Market Road & 5th Ave Intersection',
    symptomFlow: [
      '16 pothole reports over 4 months',
      'Cold-patch asphalt washed out 3 times',
      'Thermal imaging detected sub-grade moisture',
    ],
    hypothesis: 'Micro-fracture in 6-inch ductile iron water transmission lateral eroding the road gravel foundation from below.',
    recommendedAction: 'Coordinate Joint Trenching: Water Bureau must clamp lateral pipe prior to final asphalt resurfacing.',
    systemicSavingsHours: 35.0,
  },
];

// 32 Seeded Realistic Civic Reports
export const INITIAL_CIVIC_REPORTS: CivicReport[] = [
  {
    id: 'REP-9042',
    userId: 'usr-cit-104',
    userName: 'Elena Rostova',
    title: 'Critical Pothole on 5th & Market St',
    description: 'Dangerous 14-inch deep pothole near pedestrian crossing on Market St. Vehicles swerving into oncoming traffic to avoid rim damage.',
    category: 'road_damage',
    severity: 'CRITICAL',
    severityScore: 94,
    confidence: 97.2,
    status: 'IN_PROGRESS',
    latitude: 37.7842,
    longitude: -122.4075,
    address: '845 Market St, Sector 14, Civic Metro',
    zone: 'Sector 14',
    department: 'Road Maintenance & Infrastructure',
    departmentConfidence: 96,
    humanReviewRequired: false,
    evidenceUrl: 'https://images.unsplash.com/photo-1515162816999-a0c47dc192f7?auto=format&fit=crop&w=1000&q=80',
    evidenceHash: 'e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855',
    duplicateScore: 91,
    similarReportsCount: 6,
    civicImpact: {
      safetyRisk: 28,
      affectedPopulation: 24,
      severity: 22,
      reportDensity: 10,
      issueAge: 8,
      totalScore: 92,
      level: 'CRITICAL',
      modelName: 'CivicFix AI Priority Model',
      estimatedPopulationAffected: 14200,
    },
    sla: {
      targetHours: 4,
      elapsedHours: 3.35,
      remainingHours: 0.65,
      status: 'AT_RISK',
      escalationContact: 'Field Ops Dispatcher #12 (415-555-0199)',
      recommendedEscalation: 'Pre-authorize emergency hot-mix asphalt crew if unassigned in next 20 mins.',
    },
    priorityRationale: {
      rank: 2,
      reasons: [
        'High safety risk: 14-inch depth causes vehicle steering deflection',
        'Directly adjacent to high-footfall pedestrian crossing',
        '6 similar citizen reports in 200m radius',
        'Unresolved for 3 hours 21 minutes during morning rush hour',
      ],
      recommendedAction: 'Deploy quick-setting asphalt cold patch and safety perimeter cones.',
      responsibleDepartment: 'Road Maintenance & Infrastructure',
    },
    masterIncident: {
      isMaster: true,
      masterId: 'INC-2048',
      mergedCount: 6,
      similarityScore: 91.4,
      duplicateReportIds: ['REP-9042', 'REP-9043', 'REP-9044', 'REP-9045', 'REP-9046', 'REP-9047'],
    },
    timeline: [
      { step: 'SUBMITTED', label: 'Report Submitted by Citizen', timestamp: '03:42:15', completed: true },
      { step: 'AI_VERIFIED', label: 'AI Computer Vision & Severity Scored', timestamp: '03:42:18', completed: true },
      { step: 'DEPARTMENT_ASSIGNED', label: 'Assigned to Road Maintenance', timestamp: '03:42:22', completed: true },
      { step: 'FIELD_NOTIFIED', label: 'Crew Truck #4 Dispatched', timestamp: '04:00:10', completed: true },
      { step: 'IN_PROGRESS', label: 'Repair in Progress', timestamp: '04:15:00', completed: true, current: true },
      { step: 'RESOLVED', label: 'Verification & Closure', timestamp: 'Pending', completed: false },
    ],
    aiAnalysis: {
      summary: 'High-velocity asphalt depression with exposed sub-base gravel. High risk of automotive tire blowout and motorcycle loss-of-control.',
      detectedObjects: ['Asphalt Cavity', 'Exposed Sub-base', 'Traffic Hazard', 'Pedestrian Crossing Zone'],
      severityReasoning: 'Impact hazard in heavy transit corridor. Proximity to high-density pedestrian zone escalates rating to 94/100.',
      recommendedAction: 'Emergency cold-patch asphalt deployment and traffic safety cone perimeter within 2 hours.',
      targetDepartment: 'Road Maintenance & Infrastructure',
      confidenceScore: 97.2,
      duplicateProbability: 91.4,
      estimatedRepairHours: 3.5,
      s3Key: 'evidence/2026/09/REP-9042/evidence.jpg',
      bedrockModel: 'anthropic.claude-3-5-sonnet-20241022-v2:0',
      inferenceLatencyMs: 842,
      boundingBoxes: [
        { label: 'Pothole Void', box: [0.35, 0.28, 0.72, 0.76], confidence: 0.98 },
        { label: 'Sub-base Cracking', box: [0.22, 0.15, 0.85, 0.88], confidence: 0.94 },
      ],
    },
    createdAt: '2026-09-08T00:15:00Z',
    updatedAt: '2026-09-08T02:30:00Z',
    stepFunctionExecutionArn: 'arn:aws:states:us-east-1:123456789012:execution:CivicFixResolutionFlow:9042-exec',
  },
  {
    id: 'REP-9043',
    userId: 'usr-cit-201',
    userName: 'Tara Simmons',
    title: 'Deep road crater in middle of Market St',
    description: 'Broke my car wheel rim hitting this massive pothole right by 5th. Please send a crew quickly.',
    category: 'road_damage',
    severity: 'CRITICAL',
    severityScore: 93,
    confidence: 96.0,
    status: 'IN_PROGRESS',
    latitude: 37.7843,
    longitude: -122.4074,
    address: '848 Market St, Sector 14, Civic Metro',
    zone: 'Sector 14',
    department: 'Road Maintenance & Infrastructure',
    departmentConfidence: 97,
    humanReviewRequired: false,
    evidenceUrl: 'https://images.unsplash.com/photo-1515162816999-a0c47dc192f7?auto=format&fit=crop&w=1000&q=80',
    evidenceHash: 'a7b3c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b111',
    duplicateScore: 94,
    similarReportsCount: 5,
    civicImpact: {
      safetyRisk: 28,
      affectedPopulation: 24,
      severity: 22,
      reportDensity: 10,
      issueAge: 8,
      totalScore: 92,
      level: 'CRITICAL',
      modelName: 'CivicFix AI Priority Model',
      estimatedPopulationAffected: 14200,
    },
    sla: {
      targetHours: 4,
      elapsedHours: 3.1,
      remainingHours: 0.9,
      status: 'AT_RISK',
      escalationContact: 'Field Ops Dispatcher #12',
    },
    priorityRationale: {
      rank: 3,
      reasons: ['Merged into Master Incident INC-2048', 'Vehicle damage confirmed by citizen'],
      recommendedAction: 'Consolidated with dispatch truck #4.',
      responsibleDepartment: 'Road Maintenance & Infrastructure',
    },
    masterIncident: {
      isMaster: false,
      masterId: 'INC-2048',
      mergedCount: 6,
      similarityScore: 94.2,
      duplicateReportIds: ['REP-9042', 'REP-9043'],
    },
    timeline: [
      { step: 'SUBMITTED', label: 'Report Submitted', timestamp: '03:48:00', completed: true },
      { step: 'AI_VERIFIED', label: 'Duplicate Cluster Detected (94% match)', timestamp: '03:48:03', completed: true },
      { step: 'DEPARTMENT_ASSIGNED', label: 'Merged with Master Incident INC-2048', timestamp: '03:48:10', completed: true },
      { step: 'FIELD_NOTIFIED', label: 'Crew Notified', timestamp: '04:00:10', completed: true },
      { step: 'IN_PROGRESS', label: 'Unified Repair Active', timestamp: '04:15:00', completed: true, current: true },
      { step: 'RESOLVED', label: 'Closure with Master', timestamp: 'Pending', completed: false },
    ],
    aiAnalysis: {
      summary: 'Duplicate incident report matching INC-2048. Pothole cavity features identical within 15 meters radius.',
      detectedObjects: ['Asphalt Cavity', 'Vehicle Hazard'],
      severityReasoning: 'Duplicate of REP-9042. Inherits critical tier.',
      recommendedAction: 'Link to Master Incident INC-2048 to prevent dual crew dispatch.',
      targetDepartment: 'Road Maintenance & Infrastructure',
      confidenceScore: 96.0,
      duplicateProbability: 94.2,
      estimatedRepairHours: 3.5,
      s3Key: 'evidence/2026/09/REP-9043/evidence.jpg',
      bedrockModel: 'anthropic.claude-3-5-sonnet-20241022-v2:0',
      inferenceLatencyMs: 610,
    },
    createdAt: '2026-09-08T00:30:00Z',
    updatedAt: '2026-09-08T02:30:00Z',
  },
  {
    id: 'REP-9039',
    userId: 'usr-cit-109',
    userName: 'Marcus Vance',
    title: 'Open Drainage Shaft directly adjacent to Elementary School',
    description: 'Cast iron storm grate missing adjacent to elementary school crosswalk. Deep 6-foot vertical drop exposing children to severe fall danger.',
    category: 'public_hazard',
    severity: 'CRITICAL',
    severityScore: 96,
    confidence: 98.6,
    status: 'ASSIGNED',
    latitude: 37.7765,
    longitude: -122.4185,
    address: '420 Campus Ave, Campus Gate, Civic Metro',
    zone: 'Campus Gate',
    department: 'Public Utilities Commission (Drainage Division)',
    departmentConfidence: 98,
    humanReviewRequired: false,
    evidenceUrl: 'https://images.unsplash.com/photo-1541888946425-d0fbb186156a?auto=format&fit=crop&w=1000&q=80',
    evidenceHash: 'c2901594917a96a92ecbc2faee79339e80a0662d5ee16629918731d68305c4ea',
    duplicateScore: 12,
    similarReportsCount: 1,
    civicImpact: {
      safetyRisk: 30,
      affectedPopulation: 25,
      severity: 25,
      reportDensity: 8,
      issueAge: 8,
      totalScore: 96,
      level: 'CRITICAL',
      modelName: 'CivicFix AI Priority Model',
      estimatedPopulationAffected: 3200,
    },
    sla: {
      targetHours: 2,
      elapsedHours: 1.4,
      remainingHours: 0.6,
      status: 'AT_RISK',
      escalationContact: 'Safety Director Chen (415-555-0811)',
      recommendedEscalation: 'Immediate perimeter cordon by local traffic wardens.',
    },
    priorityRationale: {
      rank: 1,
      reasons: [
        'Acute life-safety risk: Uncovered vertical drop in child walking zone',
        'Directly adjacent to primary school drop-off crosswalk',
        'High foot-traffic concentration during morning arrival (8:00 AM)',
        'Unresolved for 1 hour 24 minutes',
      ],
      recommendedAction: 'Emergency police tape cordon and temporary steel road plate installation.',
      responsibleDepartment: 'Public Utilities Commission (Drainage Division)',
    },
    timeline: [
      { step: 'SUBMITTED', label: 'Report Submitted', timestamp: '01:50:00', completed: true },
      { step: 'AI_VERIFIED', label: 'Identified Missing Cover (Score 96)', timestamp: '01:50:04', completed: true },
      { step: 'DEPARTMENT_ASSIGNED', label: 'Direct Escalate to Drainage Team', timestamp: '01:50:12', completed: true, current: true },
      { step: 'FIELD_NOTIFIED', label: 'Emergency Truck #2 Alerted', timestamp: 'Pending', completed: false },
      { step: 'IN_PROGRESS', label: 'Plate Installation', timestamp: 'Pending', completed: false },
      { step: 'RESOLVED', label: 'Permanent Grate Secured', timestamp: 'Pending', completed: false },
    ],
    aiAnalysis: {
      summary: 'Missing municipal catch basin grate with vertical void exposed. Unrestricted access creates fatal pediatric fall hazard.',
      detectedObjects: ['Missing Manhole Grate', 'Uncovered Pit', 'School Zone Safety Hazard'],
      severityReasoning: 'Top priority public hazard classification due to child demographic proximity.',
      recommendedAction: 'Immediate barricade installation, steel trench plate cover, and rapid fabrication of replacement grate.',
      targetDepartment: 'Public Utilities Commission (Drainage Division)',
      confidenceScore: 98.6,
      duplicateProbability: 12.1,
      estimatedRepairHours: 2.0,
      s3Key: 'evidence/2026/09/REP-9039/evidence.jpg',
      bedrockModel: 'anthropic.claude-3-5-sonnet-20241022-v2:0',
      inferenceLatencyMs: 780,
    },
    createdAt: '2026-09-08T01:50:00Z',
    updatedAt: '2026-09-08T02:10:00Z',
    stepFunctionExecutionArn: 'arn:aws:states:us-east-1:123456789012:execution:CivicFixResolutionFlow:9039-exec',
  },
  {
    id: 'REP-9038',
    userId: 'usr-cit-109',
    userName: 'Marcus Vance',
    title: 'Severed Streetlight Conduit & Live Sparking Wire',
    description: 'Municipal streetlight pole bent at 45-degree angle with sparking electrical lines exposed to sidewalk near bus stop.',
    category: 'streetlights',
    severity: 'CRITICAL',
    severityScore: 92,
    confidence: 98.4,
    status: 'ASSIGNED',
    latitude: 37.7735,
    longitude: -122.4172,
    address: '1420 Mission St, Sector 14, Civic Metro',
    zone: 'Sector 14',
    department: 'Municipal Electrical & Power Bureau',
    departmentConfidence: 96,
    humanReviewRequired: false,
    evidenceUrl: 'https://images.unsplash.com/photo-1509114397022-ed747cca3f65?auto=format&fit=crop&w=1000&q=80',
    evidenceHash: 'd2901594917a96a92ecbc2faee79339e80a0662d5ee16629918731d68305c4ea',
    duplicateScore: 12,
    similarReportsCount: 1,
    civicImpact: {
      safetyRisk: 26,
      affectedPopulation: 18,
      severity: 22,
      reportDensity: 6,
      issueAge: 4,
      totalScore: 76,
      level: 'HIGH',
      modelName: 'CivicFix AI Priority Model',
      estimatedPopulationAffected: 4500,
    },
    sla: {
      targetHours: 4,
      elapsedHours: 1.8,
      remainingHours: 2.2,
      status: 'ON_TRACK',
      escalationContact: 'Power Bureau Grid Safety',
    },
    priorityRationale: {
      rank: 4,
      reasons: ['Sparking 240V lines at pedestrian height', 'Wet ground conditions increase conductivity'],
      recommendedAction: 'Remote de-energize pole circuit breaker 14-C.',
      responsibleDepartment: 'Municipal Electrical & Power Bureau',
    },
    timeline: [
      { step: 'SUBMITTED', label: 'Report Submitted', timestamp: '01:10:00', completed: true },
      { step: 'AI_VERIFIED', label: 'Arc Flash Hazard Confirmed', timestamp: '01:10:03', completed: true },
      { step: 'DEPARTMENT_ASSIGNED', label: 'Assigned to Power Bureau', timestamp: '01:10:15', completed: true, current: true },
      { step: 'FIELD_NOTIFIED', label: 'Bucket Truck Dispatched', timestamp: 'Pending', completed: false },
      { step: 'IN_PROGRESS', label: 'Cable Isolation', timestamp: 'Pending', completed: false },
      { step: 'RESOLVED', label: 'Mast Replaced', timestamp: 'Pending', completed: false },
    ],
    aiAnalysis: {
      summary: 'Impact-damaged luminaire pole with live 240V multi-phase wiring exposed. Severe electrocution hazard under ambient moisture conditions.',
      detectedObjects: ['Live Wiring', 'Deformed Aluminum Pole', 'Active Arc Flash Risk'],
      severityReasoning: 'Life safety threat adjacent to public school zone.',
      recommendedAction: 'Immediate high-voltage circuit de-energization and utility boom truck dispatch.',
      targetDepartment: 'Municipal Electrical & Power Bureau',
      confidenceScore: 98.4,
      duplicateProbability: 12.1,
      estimatedRepairHours: 2.0,
      s3Key: 'evidence/2026/09/REP-9038/evidence.jpg',
      bedrockModel: 'anthropic.claude-3-5-sonnet-20241022-v2:0',
      inferenceLatencyMs: 720,
    },
    createdAt: '2026-09-08T01:10:00Z',
    updatedAt: '2026-09-08T01:45:00Z',
    stepFunctionExecutionArn: 'arn:aws:states:us-east-1:123456789012:execution:CivicFixResolutionFlow:9038-exec',
  },
  {
    id: 'REP-9021',
    userId: 'usr-cit-112',
    userName: 'David Cho',
    title: 'Severe Waste Accumulation & Fire Exit Obstruction',
    description: 'Six municipal waste bins overflowing with mixed commercial refuse, broken glass, and bio-hazard chemical containers blocking emergency egress.',
    category: 'garbage_overflow',
    severity: 'HIGH',
    severityScore: 81,
    confidence: 93.8,
    status: 'IN_PROGRESS',
    latitude: 37.7884,
    longitude: -122.3989,
    address: '562 Howard St, Market Road, Civic Metro',
    zone: 'Market Road',
    department: 'Sanitation & Waste Management',
    departmentConfidence: 94,
    humanReviewRequired: false,
    evidenceUrl: 'https://images.unsplash.com/photo-1605600659873-d808a13e4d2a?auto=format&fit=crop&w=1000&q=80',
    evidenceHash: '4355a46b19d348dc2f57c046f8ef63d4538ebb936000f3c9ee954a27460dd865',
    duplicateScore: 24,
    similarReportsCount: 3,
    civicImpact: {
      safetyRisk: 22,
      affectedPopulation: 22,
      severity: 20,
      reportDensity: 10,
      issueAge: 7,
      totalScore: 81,
      level: 'HIGH',
      modelName: 'CivicFix AI Priority Model',
      estimatedPopulationAffected: 8900,
    },
    sla: {
      targetHours: 8,
      elapsedHours: 9.2,
      remainingHours: 0,
      status: 'OVERDUE',
      escalationContact: 'Sanitation Superintendent Walker',
      recommendedEscalation: 'OVERDUE BY 1H 12M — Reassign to private contractor overflow fleet immediately.',
    },
    priorityRationale: {
      rank: 5,
      reasons: [
        'Combustible waste blocking commercial building fire exit',
        'Biological contamination and rodent vector threat',
        'OVERDUE past standard 8-hour sanitation resolution target',
      ],
      recommendedAction: 'Dispatch hydraulic compactor truck with biohazard team.',
      responsibleDepartment: 'Sanitation & Waste Management',
    },
    timeline: [
      { step: 'SUBMITTED', label: 'Report Submitted', timestamp: 'Yesterday 17:40', completed: true },
      { step: 'AI_VERIFIED', label: 'Biohazard & Egress Risk Identified', timestamp: 'Yesterday 17:41', completed: true },
      { step: 'DEPARTMENT_ASSIGNED', label: 'Assigned to Sanitation Bureau', timestamp: 'Yesterday 17:45', completed: true },
      { step: 'FIELD_NOTIFIED', label: 'Shift Handover Dispatched', timestamp: 'Today 01:00', completed: true },
      { step: 'IN_PROGRESS', label: 'Compactor Crew on Scene', timestamp: 'Today 02:20', completed: true, current: true },
      { step: 'RESOLVED', label: 'Awaiting Washdown Photo', timestamp: 'Pending', completed: false },
    ],
    aiAnalysis: {
      summary: 'Accumulation of uncontained combustible and biological waste obstructing fire exit corridor.',
      detectedObjects: ['Uncontained Refuse', 'Biological Waste', 'Emergency Egress Obstruction'],
      severityReasoning: 'Fire safety violation and pest vector proliferation.',
      recommendedAction: 'Bulk refuse compactor truck dispatch and public sanitation sanitization wash.',
      targetDepartment: 'Sanitation & Waste Management',
      confidenceScore: 93.8,
      duplicateProbability: 24.3,
      estimatedRepairHours: 4.0,
      s3Key: 'evidence/2026/09/REP-9021/evidence.jpg',
      bedrockModel: 'anthropic.claude-3-5-sonnet-20241022-v2:0',
      inferenceLatencyMs: 910,
    },
    createdAt: '2026-09-07T14:02:00Z',
    updatedAt: '2026-09-08T02:00:00Z',
    stepFunctionExecutionArn: 'arn:aws:states:us-east-1:123456789012:execution:CivicFixResolutionFlow:9021-exec',
  },
  {
    id: 'REP-8995',
    userId: 'usr-cit-098',
    userName: 'Sarah Jenkins',
    title: 'High-Pressure Water Main Burst & Pavement Uplift',
    description: 'Water bubbling violently through asphalt fissure, causing foundation erosion and street flooding across two lanes.',
    category: 'water_leak',
    severity: 'CRITICAL',
    severityScore: 92,
    confidence: 96.5,
    status: 'RESOLVED',
    latitude: 37.7712,
    longitude: -122.4285,
    address: '2201 Shattuck Ave, Waterfront District, Civic Metro',
    zone: 'Waterfront District',
    department: 'Public Utilities Commission (Water Division)',
    departmentConfidence: 96,
    humanReviewRequired: false,
    evidenceUrl: 'https://images.unsplash.com/photo-1547683905-f686c993aae5?auto=format&fit=crop&w=1000&q=80',
    evidenceHash: '53c234e5e8472b6ac51c1ae1cab3fe06fad053beb8ebfd8977b010655bfdd3c3',
    duplicateScore: 6,
    similarReportsCount: 1,
    civicImpact: {
      safetyRisk: 24,
      affectedPopulation: 22,
      severity: 22,
      reportDensity: 8,
      issueAge: 4,
      totalScore: 80,
      level: 'HIGH',
      modelName: 'CivicFix AI Priority Model',
      estimatedPopulationAffected: 16500,
    },
    sla: {
      targetHours: 6,
      elapsedHours: 4.8,
      remainingHours: 0,
      status: 'ON_TRACK',
      escalationContact: 'Water Division Superintendent',
    },
    priorityRationale: {
      rank: 6,
      reasons: ['Sub-pavement erosion creates sinkhole collapse hazard', 'Potable water supply loss'],
      recommendedAction: 'Rapid isolation valve closure followed by pipe sleeve replacement.',
      responsibleDepartment: 'Public Utilities Commission (Water Division)',
    },
    resolutionProof: {
      beforeImageUrl: 'https://images.unsplash.com/photo-1547683905-f686c993aae5?auto=format&fit=crop&w=1000&q=80',
      afterImageUrl: 'https://images.unsplash.com/photo-1578916171728-46686eac8d58?auto=format&fit=crop&w=1000&q=80',
      verifiedAt: '2026-09-07T16:00:00Z',
      verifiedBy: 'Inspector David Rodriguez (Badge #4812)',
      notes: '12-inch ductile iron collar replaced and pressure tested to 85 PSI. Sub-base recompacted and hot asphalt poured. Zero residual leakage.',
    },
    timeline: [
      { step: 'SUBMITTED', label: 'Report Submitted', timestamp: 'Yesterday 09:12', completed: true },
      { step: 'AI_VERIFIED', label: 'Hydrostatic Rupture Detected', timestamp: 'Yesterday 09:12', completed: true },
      { step: 'DEPARTMENT_ASSIGNED', label: 'Water Division Mobilized', timestamp: 'Yesterday 09:18', completed: true },
      { step: 'FIELD_NOTIFIED', label: 'Valve Crew on Site', timestamp: 'Yesterday 09:45', completed: true },
      { step: 'IN_PROGRESS', label: 'Sleeve Replaced & Backfilled', timestamp: 'Yesterday 13:00', completed: true },
      { step: 'RESOLVED', label: 'Resolution Evidence Verified', timestamp: 'Yesterday 16:00', completed: true },
    ],
    aiAnalysis: {
      summary: '12-inch potable transmission main failure causing hydro-fracturing of structural roadway pavement.',
      detectedObjects: ['Hydrostatic Fissure', 'Sub-pavement Erosion', 'Localized Flooding'],
      severityReasoning: 'Water resource depletion and acute sinkhole creation hazard.',
      recommendedAction: 'Valve isolation team dispatch to halt hydrostatic pressure and prevent road subsidence.',
      targetDepartment: 'Public Utilities Commission (Water Division)',
      confidenceScore: 96.5,
      duplicateProbability: 6.2,
      estimatedRepairHours: 6.0,
      s3Key: 'evidence/2026/09/REP-8995/evidence.jpg',
      bedrockModel: 'anthropic.claude-3-5-sonnet-20241022-v2:0',
      inferenceLatencyMs: 830,
    },
    createdAt: '2026-09-06T09:12:00Z',
    updatedAt: '2026-09-06T15:40:00Z',
    resolvedAt: '2026-09-06T16:00:00Z',
    stepFunctionExecutionArn: 'arn:aws:states:us-east-1:123456789012:execution:CivicFixResolutionFlow:8995-exec',
  },
  {
    id: 'REP-8980',
    userId: 'usr-cit-084',
    userName: 'Aisha Patel',
    title: 'Shattered Pedestrian Guardrail on Overpass',
    description: 'Vehicle impact knocked down 15 feet of metal safety railing over active commuter rail tracks below.',
    category: 'infrastructure',
    severity: 'HIGH',
    severityScore: 88,
    confidence: 95.1,
    status: 'RESOLVED',
    latitude: 37.7654,
    longitude: -122.4012,
    address: 'Mariposa St & I-280 Overpass, Industrial Corridor, Civic Metro',
    zone: 'Industrial Corridor',
    department: 'Structural Engineering & Bridges',
    departmentConfidence: 95,
    humanReviewRequired: false,
    evidenceUrl: 'https://images.unsplash.com/photo-1544620347-c4fd4a3d5957?auto=format&fit=crop&w=1000&q=80',
    evidenceHash: '9f86d081884c7d659a2feaa0c55ad015a3bf4f1b2b0b822cd15d6c15b0f00a08',
    duplicateScore: 15,
    similarReportsCount: 2,
    civicImpact: {
      safetyRisk: 25,
      affectedPopulation: 19,
      severity: 22,
      reportDensity: 4,
      issueAge: 5,
      totalScore: 75,
      level: 'HIGH',
      modelName: 'CivicFix AI Priority Model',
      estimatedPopulationAffected: 7800,
    },
    sla: {
      targetHours: 12,
      elapsedHours: 9.5,
      remainingHours: 0,
      status: 'ON_TRACK',
      escalationContact: 'Bridges & Safety Engineer',
    },
    priorityRationale: {
      rank: 7,
      reasons: ['Fall hazard onto high-voltage electrified rail tracks', 'Pedestrian overpass unprotected'],
      recommendedAction: 'Deploy reinforced concrete jersey barrier and steel fence modular extension.',
      responsibleDepartment: 'Structural Engineering & Bridges',
    },
    resolutionProof: {
      beforeImageUrl: 'https://images.unsplash.com/photo-1544620347-c4fd4a3d5957?auto=format&fit=crop&w=1000&q=80',
      afterImageUrl: 'https://images.unsplash.com/photo-1578916171728-46686eac8d58?auto=format&fit=crop&w=1000&q=80',
      verifiedAt: '2026-09-06T18:00:00Z',
      verifiedBy: 'Lead Bridge Structural Engineer K. Miller',
      notes: 'Permanent galvanized steel truss guardrail anchored into reinforced bridge decking with epoxied Hilti bolts.',
    },
    timeline: [
      { step: 'SUBMITTED', label: 'Report Submitted', timestamp: 'Sep 05 20:15', completed: true },
      { step: 'AI_VERIFIED', label: 'Structural Safety Breach Scored', timestamp: 'Sep 05 20:16', completed: true },
      { step: 'DEPARTMENT_ASSIGNED', label: 'Bridge Engineering Dispatched', timestamp: 'Sep 05 20:25', completed: true },
      { step: 'FIELD_NOTIFIED', label: 'Jersey Barriers Deployed', timestamp: 'Sep 05 21:30', completed: true },
      { step: 'IN_PROGRESS', label: 'Permanent Welding Crew Active', timestamp: 'Sep 06 08:30', completed: true },
      { step: 'RESOLVED', label: 'Full Structural Proof Certified', timestamp: 'Sep 06 18:00', completed: true },
    ],
    aiAnalysis: {
      summary: 'Structural barrier failure creating imminent fall danger onto active electrified railway.',
      detectedObjects: ['Sheared Barrier', 'Railway Proximity', 'Fall Hazard'],
      severityReasoning: 'Critical pedestrian safety vulnerability on elevated transit overpass.',
      recommendedAction: 'Rapid deployment of jersey barriers and steel mesh containment.',
      targetDepartment: 'Structural Engineering & Bridges',
      confidenceScore: 95.1,
      duplicateProbability: 15.0,
      estimatedRepairHours: 5.0,
      s3Key: 'evidence/2026/09/REP-8980/evidence.jpg',
      bedrockModel: 'anthropic.claude-3-5-sonnet-20241022-v2:0',
      inferenceLatencyMs: 890,
    },
    createdAt: '2026-09-05T20:15:00Z',
    updatedAt: '2026-09-06T18:00:00Z',
    resolvedAt: '2026-09-06T18:00:00Z',
    stepFunctionExecutionArn: 'arn:aws:states:us-east-1:123456789012:execution:CivicFixResolutionFlow:8980-exec',
  },
  {
    id: 'REP-8965',
    userId: 'usr-cit-073',
    userName: 'Carlos Gomez',
    title: 'Submerged Storm Drain Causing Street Ponding',
    description: 'Heavy leaf debris and tree branches completely clogging catch basin, causing 8 inches of standing water.',
    category: 'water_leak',
    severity: 'MEDIUM',
    severityScore: 62,
    confidence: 91.0,
    status: 'AI_VERIFIED',
    latitude: 37.7915,
    longitude: -122.4140,
    address: '1100 California St, Sector 14, Civic Metro',
    zone: 'Sector 14',
    department: 'Public Utilities Commission (Sewer Division)',
    departmentConfidence: 91,
    humanReviewRequired: false,
    evidenceUrl: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?auto=format&fit=crop&w=1000&q=80',
    evidenceHash: 'b5a2c96250612366ac8e4736817735cac4f07cd1f483d0ac0d496d222995214e',
    duplicateScore: 35,
    similarReportsCount: 4,
    civicImpact: {
      safetyRisk: 16,
      affectedPopulation: 14,
      severity: 15,
      reportDensity: 8,
      issueAge: 5,
      totalScore: 58,
      level: 'MODERATE',
      modelName: 'CivicFix AI Priority Model',
      estimatedPopulationAffected: 2100,
    },
    sla: {
      targetHours: 12,
      elapsedHours: 4.5,
      remainingHours: 7.5,
      status: 'ON_TRACK',
      escalationContact: 'Sewer Maintenance Dispatch',
    },
    priorityRationale: {
      rank: 8,
      reasons: ['Localized hydroplaning hazard', 'Ponding restricts sidewalk curb access'],
      recommendedAction: 'Dispatch high-flow vacuum extraction truck.',
      responsibleDepartment: 'Public Utilities Commission (Sewer Division)',
    },
    timeline: [
      { step: 'SUBMITTED', label: 'Report Submitted', timestamp: 'Today 00:30', completed: true },
      { step: 'AI_VERIFIED', label: 'Catchment Blindness Identified', timestamp: 'Today 00:31', completed: true, current: true },
      { step: 'DEPARTMENT_ASSIGNED', label: 'Queued in Sewer Division Backlog', timestamp: 'Pending', completed: false },
      { step: 'FIELD_NOTIFIED', label: 'Vacuum Truck Assigned', timestamp: 'Pending', completed: false },
      { step: 'IN_PROGRESS', label: 'Drainage Cleared', timestamp: 'Pending', completed: false },
      { step: 'RESOLVED', label: 'Complete', timestamp: 'Pending', completed: false },
    ],
    aiAnalysis: {
      summary: 'Storm drain grated inlet blinded by particulate debris.',
      detectedObjects: ['Clogged Storm Grate', 'Surface Water Ponding'],
      severityReasoning: 'Nuisance flooding; low structural threat but localized hydroplaning hazard.',
      recommendedAction: 'Vacuum truck clear-out of catchment chamber.',
      targetDepartment: 'Public Utilities Commission (Sewer Division)',
      confidenceScore: 91.0,
      duplicateProbability: 35.2,
      estimatedRepairHours: 1.5,
      s3Key: 'evidence/2026/09/REP-8965/evidence.jpg',
      bedrockModel: 'anthropic.claude-3-5-sonnet-20241022-v2:0',
      inferenceLatencyMs: 650,
    },
    createdAt: '2026-09-08T00:30:00Z',
    updatedAt: '2026-09-08T00:45:00Z',
    stepFunctionExecutionArn: 'arn:aws:states:us-east-1:123456789012:execution:CivicFixResolutionFlow:8965-exec',
  },
  {
    id: 'REP-8940',
    userId: 'usr-cit-061',
    userName: 'Sophie Chen',
    title: 'Faded School Crosswalk Markings',
    description: 'Crosswalk stripes on 16th St outside elementary school completely worn down by bus traffic.',
    category: 'road_damage',
    severity: 'MEDIUM',
    severityScore: 58,
    confidence: 89.4,
    status: 'RESOLVED',
    latitude: 37.7645,
    longitude: -122.4210,
    address: '2100 16th St, Campus Gate, Civic Metro',
    zone: 'Campus Gate',
    department: 'Traffic Engineering & Markings',
    departmentConfidence: 89,
    humanReviewRequired: false,
    evidenceUrl: 'https://images.unsplash.com/photo-1494526585095-c41746248156?auto=format&fit=crop&w=1000&q=80',
    evidenceHash: '5e884898da28047151d0e56f8dc6292773603d0d6aabbdd62a11ef721d1542d8',
    duplicateScore: 18,
    similarReportsCount: 2,
    civicImpact: {
      safetyRisk: 14,
      affectedPopulation: 14,
      severity: 12,
      reportDensity: 4,
      issueAge: 6,
      totalScore: 50,
      level: 'MODERATE',
      modelName: 'CivicFix AI Priority Model',
      estimatedPopulationAffected: 1800,
    },
    sla: {
      targetHours: 24,
      elapsedHours: 18.0,
      remainingHours: 0,
      status: 'ON_TRACK',
      escalationContact: 'Traffic Safety Director',
    },
    priorityRationale: {
      rank: 9,
      reasons: ['Pedestrian visibility reduced at school gate', 'Scheduled for off-peak paint application'],
      recommendedAction: 'Restripe with hot-applied retroreflective thermoplastic.',
      responsibleDepartment: 'Traffic Engineering & Markings',
    },
    resolutionProof: {
      beforeImageUrl: 'https://images.unsplash.com/photo-1494526585095-c41746248156?auto=format&fit=crop&w=1000&q=80',
      afterImageUrl: 'https://images.unsplash.com/photo-1578916171728-46686eac8d58?auto=format&fit=crop&w=1000&q=80',
      verifiedAt: '2026-09-05T17:30:00Z',
      verifiedBy: 'Traffic Superintendent O’Neill',
      notes: 'Thermal glass-bead white striping applied across 4 lanes. Luminance coefficient certified compliant.',
    },
    timeline: [
      { step: 'SUBMITTED', label: 'Report Submitted', timestamp: 'Sep 04 15:20', completed: true },
      { step: 'AI_VERIFIED', label: 'Erosion Quantified (58%)', timestamp: 'Sep 04 15:22', completed: true },
      { step: 'DEPARTMENT_ASSIGNED', label: 'Traffic Marking Crew Queued', timestamp: 'Sep 04 16:00', completed: true },
      { step: 'FIELD_NOTIFIED', label: 'Night Shift Assigned', timestamp: 'Sep 05 02:00', completed: true },
      { step: 'IN_PROGRESS', label: 'Thermoplastic Application', timestamp: 'Sep 05 14:00', completed: true },
      { step: 'RESOLVED', label: 'Approved by Inspector', timestamp: 'Sep 05 17:30', completed: true },
    ],
    aiAnalysis: {
      summary: 'Retroreflective thermoplastic pavement markings eroded past visibility thresholds.',
      detectedObjects: ['Faded Road Markings', 'School Zone'],
      severityReasoning: 'Visual guidance reduction in designated child transit perimeter.',
      recommendedAction: 'Schedule thermoplastic line re-application during off-peak weekend hours.',
      targetDepartment: 'Traffic Engineering & Markings',
      confidenceScore: 89.4,
      duplicateProbability: 18.0,
      estimatedRepairHours: 3.0,
      s3Key: 'evidence/2026/09/REP-8940/evidence.jpg',
      bedrockModel: 'anthropic.claude-3-5-sonnet-20241022-v2:0',
      inferenceLatencyMs: 590,
    },
    createdAt: '2026-09-04T15:20:00Z',
    updatedAt: '2026-09-05T17:30:00Z',
    resolvedAt: '2026-09-05T17:30:00Z',
    stepFunctionExecutionArn: 'arn:aws:states:us-east-1:123456789012:execution:CivicFixResolutionFlow:8940-exec',
  },
  {
    id: 'REP-8922',
    userId: 'usr-cit-049',
    userName: 'Liam O’Connor',
    title: 'Graffiti Defacement on Civic Library Facade',
    description: 'Aerosol paint tag covering architectural limestone entrance columns of district public library.',
    category: 'public_hazard',
    severity: 'LOW',
    severityScore: 32,
    confidence: 94.7,
    status: 'ASSIGNED',
    latitude: 37.7780,
    longitude: -122.4160,
    address: '100 Larkin St, Old Town Heritage, Civic Metro',
    zone: 'Old Town Heritage',
    department: 'Civic Blight & Graffiti Abatement',
    departmentConfidence: 95,
    humanReviewRequired: false,
    evidenceUrl: 'https://images.unsplash.com/photo-1528747045269-390fe33c19f2?auto=format&fit=crop&w=1000&q=80',
    evidenceHash: '4b227777d4dd1fc61c6f884f48641d02b4d121d3fd328cb08b5531fcacdabf8a',
    duplicateScore: 4,
    similarReportsCount: 0,
    civicImpact: {
      safetyRisk: 6,
      affectedPopulation: 8,
      severity: 8,
      reportDensity: 2,
      issueAge: 2,
      totalScore: 26,
      level: 'LOW',
      modelName: 'CivicFix AI Priority Model',
      estimatedPopulationAffected: 950,
    },
    sla: {
      targetHours: 48,
      elapsedHours: 12.0,
      remainingHours: 36.0,
      status: 'ON_TRACK',
      escalationContact: 'Blight Removal Office',
    },
    priorityRationale: {
      rank: 10,
      reasons: ['Superficial aesthetic paint tag on heritage substrate', 'Zero life-safety risk'],
      recommendedAction: 'Chemical wash with eco-friendly graffiti solvent.',
      responsibleDepartment: 'Civic Blight & Graffiti Abatement',
    },
    timeline: [
      { step: 'SUBMITTED', label: 'Report Submitted', timestamp: 'Sep 04 08:15', completed: true },
      { step: 'AI_VERIFIED', label: 'Categorized Non-Hazardous', timestamp: 'Sep 04 08:16', completed: true },
      { step: 'DEPARTMENT_ASSIGNED', label: 'Assigned to Graffiti Removal', timestamp: 'Sep 04 09:00', completed: true, current: true },
      { step: 'FIELD_NOTIFIED', label: 'Wash Van Scheduled', timestamp: 'Pending', completed: false },
      { step: 'IN_PROGRESS', label: 'Cleaning Active', timestamp: 'Pending', completed: false },
      { step: 'RESOLVED', label: 'Restoration Proof', timestamp: 'Pending', completed: false },
    ],
    aiAnalysis: {
      summary: 'Non-structural superficial paint application on historic masonry.',
      detectedObjects: ['Aerosol Graffiti', 'Limestone Substrate'],
      severityReasoning: 'Aesthetic and civic maintenance issue without structural or life safety risk.',
      recommendedAction: 'Deploy non-toxic chemical stripper and micro-abrasive pressure wash.',
      targetDepartment: 'Civic Blight & Graffiti Abatement',
      confidenceScore: 94.7,
      duplicateProbability: 4.1,
      estimatedRepairHours: 2.0,
      s3Key: 'evidence/2026/09/REP-8922/evidence.jpg',
      bedrockModel: 'anthropic.claude-3-5-sonnet-20241022-v2:0',
      inferenceLatencyMs: 510,
    },
    createdAt: '2026-09-04T08:15:00Z',
    updatedAt: '2026-09-04T09:00:00Z',
    stepFunctionExecutionArn: 'arn:aws:states:us-east-1:123456789012:execution:CivicFixResolutionFlow:8922-exec',
  },
];

// Generate an additional 22 reports programmatically to ensure full 30+ coverage
const categoriesPool: Array<CivicReport['category']> = [
  'road_damage',
  'streetlights',
  'garbage_overflow',
  'water_leak',
  'public_hazard',
  'infrastructure',
];

const zonesPool = ['Sector 14', 'Campus Gate', 'Market Road', 'Industrial Corridor', 'Waterfront District', 'Old Town Heritage'];
const streetsPool = ['Pine St', 'Folsom St', 'Geary Blvd', 'Valencia St', 'Embarcadero', 'Columbus Ave', 'King St', '7th St'];

for (let i = 11; i <= 32; i++) {
  const cat = categoriesPool[i % categoriesPool.length];
  const zone = zonesPool[i % zonesPool.length];
  const street = streetsPool[i % streetsPool.length];
  const isCritical = i % 4 === 0;
  const isOverdue = i % 5 === 0;
  const score = isCritical ? 90 + (i % 6) : 45 + (i % 35);
  const impact = Math.min(98, score + (i % 4));

  INITIAL_CIVIC_REPORTS.push({
    id: `REP-89${i < 10 ? '0' + i : i}`,
    userId: `usr-cit-${100 + i}`,
    userName: `Citizen Reporter #${100 + i}`,
    title: `${cat.replace('_', ' ').toUpperCase()}: Maintenance needed on ${street}`,
    description: `Reported incident regarding ${cat.replace('_', ' ')} observed along ${street} in ${zone}. Requires municipal department inspection.`,
    category: cat,
    severity: isCritical ? 'CRITICAL' : score > 70 ? 'HIGH' : 'MEDIUM',
    severityScore: score,
    confidence: 90 + (i % 9),
    status: isCritical ? 'IN_PROGRESS' : i % 3 === 0 ? 'RESOLVED' : 'ASSIGNED',
    latitude: 37.7700 + (i * 0.0015),
    longitude: -122.4100 - (i * 0.0012),
    address: `${200 + i * 15} ${street}, ${zone}, Civic Metro`,
    zone: zone,
    department:
      cat === 'road_damage'
        ? 'Road Maintenance & Infrastructure'
        : cat === 'streetlights'
        ? 'Municipal Electrical & Power Bureau'
        : cat === 'garbage_overflow'
        ? 'Sanitation & Waste Management'
        : cat === 'water_leak'
        ? 'Public Utilities Commission (Water Division)'
        : cat === 'infrastructure'
        ? 'Structural Engineering & Bridges'
        : 'Public Safety Department',
    departmentConfidence: 92,
    humanReviewRequired: false,
    evidenceUrl: 'https://images.unsplash.com/photo-1515162816999-a0c47dc192f7?auto=format&fit=crop&w=1000&q=80',
    evidenceHash: `hash-${i}-f7b99214`,
    duplicateScore: (i * 3) % 25,
    similarReportsCount: (i % 4),
    civicImpact: {
      safetyRisk: isCritical ? 28 : 16,
      affectedPopulation: 18,
      severity: Math.floor(score * 0.25),
      reportDensity: 6,
      issueAge: 4,
      totalScore: impact,
      level: impact >= 90 ? 'CRITICAL' : impact >= 70 ? 'HIGH' : 'MODERATE',
      modelName: 'CivicFix AI Priority Model',
      estimatedPopulationAffected: 3000 + i * 400,
    },
    sla: {
      targetHours: isCritical ? 4 : 24,
      elapsedHours: isOverdue ? 26 : 8,
      remainingHours: isOverdue ? 0 : 16,
      status: isOverdue ? 'OVERDUE' : isCritical ? 'AT_RISK' : 'ON_TRACK',
      escalationContact: 'Municipal Dispatch Desk',
      recommendedEscalation: isOverdue ? 'OVERDUE: Escalate to Section Chief for expedited crew deployment.' : undefined,
    },
    priorityRationale: {
      rank: i,
      reasons: [
        `${cat.replace('_', ' ')} along ${street}`,
        `Civic Impact rating: ${impact}/100 based on area footfall and density`,
      ],
      recommendedAction: 'Standard municipal field assessment and resolution.',
      responsibleDepartment: 'Municipal Works',
    },
    timeline: [
      { step: 'SUBMITTED', label: 'Report Submitted', timestamp: 'Today 04:00', completed: true },
      { step: 'AI_VERIFIED', label: 'AI Classified', timestamp: 'Today 04:01', completed: true },
      { step: 'DEPARTMENT_ASSIGNED', label: 'Department Assigned', timestamp: 'Today 04:05', completed: true },
      { step: 'FIELD_NOTIFIED', label: 'Crew Notified', timestamp: 'Today 04:30', completed: true },
      { step: 'IN_PROGRESS', label: 'Under Repair', timestamp: 'Today 05:00', completed: isCritical, current: isCritical },
      { step: 'RESOLVED', label: 'Completed', timestamp: 'Pending', completed: i % 3 === 0 },
    ],
    aiAnalysis: {
      summary: `Automated vision classification for ${cat} incident located at ${street}.`,
      detectedObjects: [cat, 'Civic Hazard'],
      severityReasoning: `Identified visual markers indicating ${isCritical ? 'high hazard' : 'standard maintenance need'}.`,
      recommendedAction: 'Standard inspection workflow dispatch.',
      targetDepartment: 'Municipal Works',
      confidenceScore: 92.4,
      duplicateProbability: 10.0,
      estimatedRepairHours: 3.0,
      s3Key: `evidence/2026/09/REP-89${i}/evidence.jpg`,
      bedrockModel: 'anthropic.claude-3-5-sonnet-20241022-v2:0',
      inferenceLatencyMs: 600 + (i * 10),
    },
    createdAt: new Date(Date.now() - (i * 3600000)).toISOString(),
    updatedAt: new Date(Date.now() - (i * 1800000)).toISOString(),
  });
}

export const INITIAL_AWS_TELEMETRY: AwsTelemetryEvent[] = [
  {
    id: 'evt-1001',
    timestamp: '03:42:18',
    service: 'Amazon Bedrock',
    action: 'InvokeModel (Claude 3.5 Sonnet)',
    details: 'Visual reasoning & severity classification complete for INC-2048 (Score: 94)',
    status: 'SUCCESS',
    latencyMs: 842,
  },
  {
    id: 'evt-1002',
    timestamp: '03:42:20',
    service: 'Amazon OpenSearch',
    action: 'kNN Vector Similarity Query',
    details: 'Duplicate analysis completed: 6 matching reports clustered (Max similarity 91.4%)',
    status: 'SUCCESS',
    latencyMs: 98,
  },
  {
    id: 'evt-1003',
    timestamp: '03:42:22',
    service: 'Amazon DynamoDB',
    action: 'PutItem (CivicFixReports & MasterIncidents)',
    details: 'Indexed INC-2048 and linked 6 citizen reports to Road Maintenance partition',
    status: 'SUCCESS',
    latencyMs: 22,
  },
  {
    id: 'evt-1004',
    timestamp: '03:42:24',
    service: 'AWS Step Functions',
    action: 'StartExecution (CivicFixResolutionFlow)',
    details: 'Execution started: arn:aws:states:us-east-1:123456789012:execution:CivicFixResolutionFlow:2048-exec',
    status: 'SUCCESS',
    latencyMs: 110,
  },
  {
    id: 'evt-1005',
    timestamp: '03:42:25',
    service: 'Amazon EventBridge',
    action: 'PutEvents (civic.events: UrgentActionTriggered)',
    details: 'Event emitted to municipal dispatch webhook and emergency crew SMS gateway',
    status: 'SUCCESS',
    latencyMs: 44,
  },
  {
    id: 'evt-1006',
    timestamp: '03:43:00',
    service: 'Amazon S3',
    action: 'PutObject (evidence/2026/09/INC-2048/evidence.jpg)',
    details: 'Client-side SHA-256 fingerprint verified; SSE-S3 256-bit AES encryption applied',
    status: 'SUCCESS',
    latencyMs: 145,
  },
];

export const SAMPLE_STEP_FUNCTION_EXECUTION: StepFunctionExecution = {
  executionArn: 'arn:aws:states:us-east-1:123456789012:execution:CivicFixResolutionFlow:9042-exec',
  reportId: 'REP-9042',
  status: 'RUNNING',
  startedAt: '2026-09-08T00:15:00Z',
  steps: [
    {
      id: 'step-1',
      name: 'Citizen Ingestion & API Gateway Validation',
      service: 'Amazon API Gateway',
      status: 'COMPLETED',
      durationMs: 84,
      timestamp: '00:15:00',
      details: 'Payload schema validated and throttled at 5,000 req/sec limit.',
    },
    {
      id: 'step-2',
      name: 'Secure S3 Evidence Archival',
      service: 'Amazon S3',
      status: 'COMPLETED',
      durationMs: 145,
      timestamp: '00:15:01',
      details: 'Stored with server-side AES-256 encryption. EXIF stripped except latitude/longitude.',
    },
    {
      id: 'step-3',
      name: 'Bedrock Multimodal Vision Reasoning',
      service: 'Amazon Bedrock',
      status: 'COMPLETED',
      durationMs: 842,
      timestamp: '00:15:02',
      details: 'Claude 3.5 Sonnet detected asphalt failure void, computed 94/100 severity.',
    },
    {
      id: 'step-4',
      name: 'OpenSearch Vector Deduplication',
      service: 'Amazon OpenSearch',
      status: 'COMPLETED',
      durationMs: 98,
      timestamp: '00:15:03',
      details: 'Vector kNN matched 6 nearby reports; consolidated into Master Incident INC-2048.',
    },
    {
      id: 'step-5',
      name: 'Civic Impact Score Model',
      service: 'AWS Lambda',
      status: 'COMPLETED',
      durationMs: 38,
      timestamp: '00:15:03',
      details: 'Calculated 92/100 Priority based on Safety (+28), Population (+24), Severity (+22).',
    },
    {
      id: 'step-6',
      name: 'EventBridge Automated Dispatch',
      service: 'Amazon EventBridge',
      status: 'RUNNING',
      durationMs: 44,
      timestamp: '00:15:04',
      details: 'Routing ticket to Road Maintenance mobile field terminals.',
    },
  ],
};
