import { CivicReport, AwsTelemetryEvent, StepFunctionExecution } from '@/types';

export const PRESET_CIVIC_EVIDENCE = [
  {
    id: 'preset-pothole',
    title: 'Severe Asphalt Cavity & Sub-base Failure',
    category: 'road_damage' as const,
    defaultDescription: 'Dangerous 14-inch deep pothole near pedestrian crossing on Market St. Vehicles swerving into oncoming traffic to avoid rim damage.',
    address: '845 Market St, San Francisco, CA 94103',
    lat: 37.7842,
    lng: -122.4075,
    imageUrl: 'https://images.unsplash.com/photo-1515162816999-a0c47dc192f7?auto=format&fit=crop&w=1000&q=80',
    severity: 'CRITICAL' as const,
    severityScore: 94,
    confidence: 97.2,
    department: 'Road Maintenance & Infrastructure',
    recommendedAction: 'Emergency cold-patch asphalt deployment and traffic safety cone perimeter within 2 hours.',
    detectedObjects: ['Asphalt Cavity', 'Exposed Rebar', 'Traffic Hazard', 'Pedestrian Crossing Zone'],
    estimatedHours: 3.5,
  },
  {
    id: 'preset-streetlight',
    title: 'Exposed Wiring on Knocked Streetlight Pole',
    category: 'streetlights' as const,
    defaultDescription: 'Municipal streetlight pole bent at 45-degree angle with sparking electrical lines exposed to sidewalk near school bus stop.',
    address: '1420 Mission St, San Francisco, CA 94103',
    lat: 37.7735,
    lng: -122.4172,
    imageUrl: 'https://images.unsplash.com/photo-1509114397022-ed747cca3f65?auto=format&fit=crop&w=1000&q=80',
    severity: 'CRITICAL' as const,
    severityScore: 96,
    confidence: 98.4,
    department: 'Municipal Electrical & Power Bureau',
    recommendedAction: 'Immediate high-voltage circuit de-energization and utility boom truck dispatch.',
    detectedObjects: ['Live Wiring', 'Deformed Aluminum Pole', 'Active Arc Flash Risk'],
    estimatedHours: 2.0,
  },
  {
    id: 'preset-garbage',
    title: 'Hazardous Waste & Alley Garbage Overflow',
    category: 'garbage_overflow' as const,
    defaultDescription: 'Six municipal waste bins overflowing with mixed commercial refuse, broken glass, and bio-hazard chemical containers blocking emergency egress.',
    address: '562 Howard St, San Francisco, CA 94105',
    lat: 37.7884,
    lng: -122.3989,
    imageUrl: 'https://images.unsplash.com/photo-1605600659873-d808a13e4d2a?auto=format&fit=crop&w=1000&q=80',
    severity: 'HIGH' as const,
    severityScore: 78,
    confidence: 93.8,
    department: 'Sanitation & Waste Management',
    recommendedAction: 'Bulk refuse compactor truck dispatch and public sanitation sanitization wash.',
    detectedObjects: ['Uncontained Refuse', 'Biological Waste', 'Emergency Egress Obstruction'],
    estimatedHours: 4.0,
  },
  {
    id: 'preset-water',
    title: 'High-Pressure Water Main Fracture & Road Uplift',
    category: 'water_leak' as const,
    defaultDescription: 'Water bubbling violently through asphalt fissure, causing foundation erosion and street flooding across two lanes.',
    address: '2201 Shattuck Ave, Berkeley, CA 94704',
    lat: 37.7712,
    lng: -122.4285,
    imageUrl: 'https://images.unsplash.com/photo-1547683905-f686c993aae5?auto=format&fit=crop&w=1000&q=80',
    severity: 'CRITICAL' as const,
    severityScore: 92,
    confidence: 96.5,
    department: 'Public Utilities Commission (Water Division)',
    recommendedAction: 'Valve isolation team dispatch to halt hydrostatic pressure and prevent road subsidence.',
    detectedObjects: ['Hydrostatic Fissure', 'Sub-pavement Erosion', 'Localized Flooding'],
    estimatedHours: 6.0,
  },
];

export const INITIAL_CIVIC_REPORTS: CivicReport[] = [
  {
    id: 'REP-9042',
    userId: 'usr-cit-104',
    userName: 'Elena Rostova',
    title: 'Critical Pothole on 5th & Market St',
    description: 'Dangerous 14-inch deep pothole near pedestrian crossing on Market St. Vehicles swerving into oncoming traffic to avoid rim damage.',
    category: 'road_damage',
    severity: 'CRITICAL',
    severityScore: 94,
    confidence: 97.2,
    status: 'IN_PROGRESS',
    latitude: 37.7842,
    longitude: -122.4075,
    address: '845 Market St, San Francisco, CA 94103',
    department: 'Road Maintenance & Infrastructure',
    evidenceUrl: 'https://images.unsplash.com/photo-1515162816999-a0c47dc192f7?auto=format&fit=crop&w=1000&q=80',
    evidenceHash: 'e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855',
    duplicateScore: 8,
    similarReportsCount: 2,
    aiAnalysis: {
      summary: 'High-velocity asphalt depression with exposed sub-base gravel. High risk of automotive tire blowout and motorcycle loss-of-control.',
      detectedObjects: ['Asphalt Cavity', 'Exposed Rebar', 'Traffic Hazard', 'Pedestrian Crossing Zone'],
      severityReasoning: 'Impact hazard in heavy transit corridor. Proximity to high-density pedestrian zone escalates rating to 94/100.',
      recommendedAction: 'Emergency cold-patch asphalt deployment and traffic safety cone perimeter within 2 hours.',
      targetDepartment: 'Road Maintenance & Infrastructure',
      confidenceScore: 97.2,
      duplicateProbability: 8.4,
      estimatedRepairHours: 3.5,
      s3Key: 'evidence/2026/09/REP-9042/evidence.jpg',
      bedrockModel: 'anthropic.claude-3-5-sonnet-20241022-v2:0',
      inferenceLatencyMs: 842,
      boundingBoxes: [
        { label: 'Pothole Void', box: [0.35, 0.28, 0.72, 0.76], confidence: 0.98 },
        { label: 'Sub-base Cracking', box: [0.22, 0.15, 0.85, 0.88], confidence: 0.94 },
      ],
    },
    createdAt: '2026-09-07T18:32:00Z',
    updatedAt: '2026-09-07T19:15:00Z',
    stepFunctionExecutionArn: 'arn:aws:states:us-east-1:123456789012:execution:CivicFixResolutionFlow:9042-exec',
  },
  {
    id: 'REP-9038',
    userId: 'usr-cit-109',
    userName: 'Marcus Vance',
    title: 'Severed Streetlight Electrical Conduit',
    description: 'Municipal streetlight pole bent at 45-degree angle with sparking electrical lines exposed to sidewalk near school bus stop.',
    category: 'streetlights',
    severity: 'CRITICAL',
    severityScore: 96,
    confidence: 98.4,
    status: 'ASSIGNED',
    latitude: 37.7735,
    longitude: -122.4172,
    address: '1420 Mission St, San Francisco, CA 94103',
    department: 'Municipal Electrical & Power Bureau',
    evidenceUrl: 'https://images.unsplash.com/photo-1509114397022-ed747cca3f65?auto=format&fit=crop&w=1000&q=80',
    evidenceHash: 'c2901594917a96a92ecbc2faee79339e80a0662d5ee16629918731d68305c4ea',
    duplicateScore: 12,
    similarReportsCount: 1,
    aiAnalysis: {
      summary: 'Impact-damaged luminaire pole with live 240V multi-phase wiring exposed. Severe electrocution hazard under ambient moisture conditions.',
      detectedObjects: ['Live Wiring', 'Deformed Aluminum Pole', 'Active Arc Flash Risk'],
      severityReasoning: 'Life safety threat adjacent to public school zone.',
      recommendedAction: 'Immediate high-voltage circuit de-energization and utility boom truck dispatch.',
      targetDepartment: 'Municipal Electrical & Power Bureau',
      confidenceScore: 98.4,
      duplicateProbability: 12.1,
      estimatedRepairHours: 2.0,
      s3Key: 'evidence/2026/09/REP-9038/evidence.jpg',
      bedrockModel: 'anthropic.claude-3-5-sonnet-20241022-v2:0',
      inferenceLatencyMs: 720,
    },
    createdAt: '2026-09-07T16:10:00Z',
    updatedAt: '2026-09-07T16:25:00Z',
    stepFunctionExecutionArn: 'arn:aws:states:us-east-1:123456789012:execution:CivicFixResolutionFlow:9038-exec',
  },
  {
    id: 'REP-9021',
    userId: 'usr-cit-112',
    userName: 'David Cho',
    title: 'Commercial Refuse Overflow Blocking Alley',
    description: 'Six municipal waste bins overflowing with mixed commercial refuse, broken glass, and bio-hazard chemical containers blocking emergency egress.',
    category: 'garbage_overflow',
    severity: 'HIGH',
    severityScore: 78,
    confidence: 93.8,
    status: 'IN_PROGRESS',
    latitude: 37.7884,
    longitude: -122.3989,
    address: '562 Howard St, San Francisco, CA 94105',
    department: 'Sanitation & Waste Management',
    evidenceUrl: 'https://images.unsplash.com/photo-1605600659873-d808a13e4d2a?auto=format&fit=crop&w=1000&q=80',
    evidenceHash: '4355a46b19d348dc2f57c046f8ef63d4538ebb936000f3c9ee954a27460dd865',
    duplicateScore: 24,
    similarReportsCount: 3,
    aiAnalysis: {
      summary: 'Accumulation of uncontained combustible and biological waste obstructing fire exit corridor.',
      detectedObjects: ['Uncontained Refuse', 'Biological Waste', 'Emergency Egress Obstruction'],
      severityReasoning: 'Fire safety violation and pest vector proliferation.',
      recommendedAction: 'Bulk refuse compactor truck dispatch and public sanitation sanitization wash.',
      targetDepartment: 'Sanitation & Waste Management',
      confidenceScore: 93.8,
      duplicateProbability: 24.3,
      estimatedRepairHours: 4.0,
      s3Key: 'evidence/2026/09/REP-9021/evidence.jpg',
      bedrockModel: 'anthropic.claude-3-5-sonnet-20241022-v2:0',
      inferenceLatencyMs: 910,
    },
    createdAt: '2026-09-07T14:02:00Z',
    updatedAt: '2026-09-07T15:00:00Z',
    stepFunctionExecutionArn: 'arn:aws:states:us-east-1:123456789012:execution:CivicFixResolutionFlow:9021-exec',
  },
  {
    id: 'REP-8995',
    userId: 'usr-cit-098',
    userName: 'Sarah Jenkins',
    title: 'High-Pressure Water Main Burst & Pavement Uplift',
    description: 'Water bubbling violently through asphalt fissure, causing foundation erosion and street flooding across two lanes.',
    category: 'water_leak',
    severity: 'CRITICAL',
    severityScore: 92,
    confidence: 96.5,
    status: 'RESOLVED',
    latitude: 37.7712,
    longitude: -122.4285,
    address: '2201 Shattuck Ave, Berkeley, CA 94704',
    department: 'Public Utilities Commission (Water Division)',
    evidenceUrl: 'https://images.unsplash.com/photo-1547683905-f686c993aae5?auto=format&fit=crop&w=1000&q=80',
    evidenceHash: '53c234e5e8472b6ac51c1ae1cab3fe06fad053beb8ebfd8977b010655bfdd3c3',
    duplicateScore: 6,
    similarReportsCount: 1,
    aiAnalysis: {
      summary: '12-inch potable transmission main failure causing hydro-fracturing of structural roadway pavement.',
      detectedObjects: ['Hydrostatic Fissure', 'Sub-pavement Erosion', 'Localized Flooding'],
      severityReasoning: 'Water resource depletion and acute sinkhole creation hazard.',
      recommendedAction: 'Valve isolation team dispatch to halt hydrostatic pressure and prevent road subsidence.',
      targetDepartment: 'Public Utilities Commission (Water Division)',
      confidenceScore: 96.5,
      duplicateProbability: 6.2,
      estimatedRepairHours: 6.0,
      s3Key: 'evidence/2026/09/REP-8995/evidence.jpg',
      bedrockModel: 'anthropic.claude-3-5-sonnet-20241022-v2:0',
      inferenceLatencyMs: 830,
    },
    createdAt: '2026-09-06T09:12:00Z',
    updatedAt: '2026-09-06T15:40:00Z',
    resolvedAt: '2026-09-06T16:00:00Z',
    stepFunctionExecutionArn: 'arn:aws:states:us-east-1:123456789012:execution:CivicFixResolutionFlow:8995-exec',
  },
  {
    id: 'REP-8980',
    userId: 'usr-cit-084',
    userName: 'Aisha Patel',
    title: 'Shattered Pedestrian Guardrail on Overpass',
    description: 'Vehicle impact knocked down 15 feet of metal safety railing over active commuter rail tracks below.',
    category: 'infrastructure',
    severity: 'HIGH',
    severityScore: 88,
    confidence: 95.1,
    status: 'IN_PROGRESS',
    latitude: 37.7654,
    longitude: -122.4012,
    address: 'Mariposa St & I-280 Overpass, San Francisco, CA',
    department: 'Structural Engineering & Bridges',
    evidenceUrl: 'https://images.unsplash.com/photo-1544620347-c4fd4a3d5957?auto=format&fit=crop&w=1000&q=80',
    evidenceHash: '9f86d081884c7d659a2feaa0c55ad015a3bf4f1b2b0b822cd15d6c15b0f00a08',
    duplicateScore: 15,
    similarReportsCount: 2,
    aiAnalysis: {
      summary: 'Structural barrier failure creating imminent fall danger onto active electrified railway.',
      detectedObjects: ['Sheared Barrier', 'Railway Proximity', 'Fall Hazard'],
      severityReasoning: 'Critical pedestrian safety vulnerability on elevated transit overpass.',
      recommendedAction: 'Rapid deployment of jersey barriers and steel mesh containment.',
      targetDepartment: 'Structural Engineering & Bridges',
      confidenceScore: 95.1,
      duplicateProbability: 15.0,
      estimatedRepairHours: 5.0,
      s3Key: 'evidence/2026/09/REP-8980/evidence.jpg',
      bedrockModel: 'anthropic.claude-3-5-sonnet-20241022-v2:0',
      inferenceLatencyMs: 890,
    },
    createdAt: '2026-09-05T20:15:00Z',
    updatedAt: '2026-09-06T08:30:00Z',
    stepFunctionExecutionArn: 'arn:aws:states:us-east-1:123456789012:execution:CivicFixResolutionFlow:8980-exec',
  },
  {
    id: 'REP-8965',
    userId: 'usr-cit-073',
    userName: 'Carlos Gomez',
    title: 'Submerged Storm Drain Causing Street Ponding',
    description: 'Heavy leaf debris and tree branches completely clogging catch basin, causing 8 inches of standing water.',
    category: 'water_leak',
    severity: 'MEDIUM',
    severityScore: 62,
    confidence: 91.0,
    status: 'AI_VERIFIED',
    latitude: 37.7915,
    longitude: -122.4140,
    address: '1100 California St, San Francisco, CA',
    department: 'Public Utilities Commission (Sewer Division)',
    evidenceUrl: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?auto=format&fit=crop&w=1000&q=80',
    evidenceHash: 'b5a2c96250612366ac8e4736817735cac4f07cd1f483d0ac0d496d222995214e',
    duplicateScore: 35,
    similarReportsCount: 4,
    aiAnalysis: {
      summary: 'Storm drain grated inlet blinded by particulate debris.',
      detectedObjects: ['Clogged Storm Grate', 'Surface Water Ponding'],
      severityReasoning: 'Nuisance flooding; low structural threat but localized hydroplaning hazard.',
      recommendedAction: 'Vacuum truck clear-out of catchment chamber.',
      targetDepartment: 'Public Utilities Commission (Sewer Division)',
      confidenceScore: 91.0,
      duplicateProbability: 35.2,
      estimatedRepairHours: 1.5,
      s3Key: 'evidence/2026/09/REP-8965/evidence.jpg',
      bedrockModel: 'anthropic.claude-3-5-sonnet-20241022-v2:0',
      inferenceLatencyMs: 650,
    },
    createdAt: '2026-09-05T11:00:00Z',
    updatedAt: '2026-09-05T11:45:00Z',
    stepFunctionExecutionArn: 'arn:aws:states:us-east-1:123456789012:execution:CivicFixResolutionFlow:8965-exec',
  },
  {
    id: 'REP-8940',
    userId: 'usr-cit-061',
    userName: 'Sophie Chen',
    title: 'Faded School Crosswalk Markings',
    description: 'Crosswalk stripes on 16th St outside elementary school completely worn down by bus traffic.',
    category: 'road_damage',
    severity: 'MEDIUM',
    severityScore: 58,
    confidence: 89.4,
    status: 'RESOLVED',
    latitude: 37.7645,
    longitude: -122.4210,
    address: '2100 16th St, San Francisco, CA',
    department: 'Traffic Engineering & Markings',
    evidenceUrl: 'https://images.unsplash.com/photo-1494526585095-c41746248156?auto=format&fit=crop&w=1000&q=80',
    evidenceHash: '5e884898da28047151d0e56f8dc6292773603d0d6aabbdd62a11ef721d1542d8',
    duplicateScore: 18,
    similarReportsCount: 2,
    aiAnalysis: {
      summary: 'Retroreflective thermoplastic pavement markings eroded past visibility thresholds.',
      detectedObjects: ['Faded Road Markings', 'School Zone'],
      severityReasoning: 'Visual guidance reduction in designated child transit perimeter.',
      recommendedAction: 'Schedule thermoplastic line re-application during off-peak weekend hours.',
      targetDepartment: 'Traffic Engineering & Markings',
      confidenceScore: 89.4,
      duplicateProbability: 18.0,
      estimatedRepairHours: 3.0,
      s3Key: 'evidence/2026/09/REP-8940/evidence.jpg',
      bedrockModel: 'anthropic.claude-3-5-sonnet-20241022-v2:0',
      inferenceLatencyMs: 590,
    },
    createdAt: '2026-09-04T15:20:00Z',
    updatedAt: '2026-09-05T17:00:00Z',
    resolvedAt: '2026-09-05T17:30:00Z',
    stepFunctionExecutionArn: 'arn:aws:states:us-east-1:123456789012:execution:CivicFixResolutionFlow:8940-exec',
  },
  {
    id: 'REP-8922',
    userId: 'usr-cit-049',
    userName: 'Liam O’Connor',
    title: 'Graffiti Defacement on Civic Library Facade',
    description: 'Aerosol paint tag covering architectural limestone entrance columns of district public library.',
    category: 'public_hazard',
    severity: 'LOW',
    severityScore: 32,
    confidence: 94.7,
    status: 'ASSIGNED',
    latitude: 37.7780,
    longitude: -122.4160,
    address: '100 Larkin St, San Francisco, CA',
    department: 'Civic Blight & Graffiti Abatement',
    evidenceUrl: 'https://images.unsplash.com/photo-1528747045269-390fe33c19f2?auto=format&fit=crop&w=1000&q=80',
    evidenceHash: '4b227777d4dd1fc61c6f884f48641d02b4d121d3fd328cb08b5531fcacdabf8a',
    duplicateScore: 4,
    similarReportsCount: 0,
    aiAnalysis: {
      summary: 'Non-structural superficial paint application on historic masonry.',
      detectedObjects: ['Aerosol Graffiti', 'Limestone Substrate'],
      severityReasoning: 'Aesthetic and civic maintenance issue without structural or life safety risk.',
      recommendedAction: 'Deploy non-toxic chemical stripper and micro-abrasive pressure wash.',
      targetDepartment: 'Civic Blight & Graffiti Abatement',
      confidenceScore: 94.7,
      duplicateProbability: 4.1,
      estimatedRepairHours: 2.0,
      s3Key: 'evidence/2026/09/REP-8922/evidence.jpg',
      bedrockModel: 'anthropic.claude-3-5-sonnet-20241022-v2:0',
      inferenceLatencyMs: 510,
    },
    createdAt: '2026-09-04T08:15:00Z',
    updatedAt: '2026-09-04T09:00:00Z',
    stepFunctionExecutionArn: 'arn:aws:states:us-east-1:123456789012:execution:CivicFixResolutionFlow:8922-exec',
  },
];

export const INITIAL_AWS_TELEMETRY: AwsTelemetryEvent[] = [
  {
    id: 'evt-1001',
    timestamp: 'Just now',
    service: 'Amazon Bedrock',
    action: 'InvokeModel (Claude 3.5 Sonnet)',
    details: 'Visual reasoning & severity classification complete for REP-9042 (Score: 94)',
    status: 'SUCCESS',
    latencyMs: 842,
  },
  {
    id: 'evt-1002',
    timestamp: '1 min ago',
    service: 'Amazon S3',
    action: 'PutObject (evidence/2026/09/REP-9042/evidence.jpg)',
    details: 'Evidence photo stored with SSE-S3 encryption and SHA-256 integrity hash',
    status: 'SUCCESS',
    latencyMs: 145,
  },
  {
    id: 'evt-1003',
    timestamp: '2 mins ago',
    service: 'Amazon OpenSearch',
    action: 'kNN Vector Similarity Query',
    details: 'Compared dense embedding vector against 1,248 civic vectors. 2 similar reports found (max similarity 8.4%)',
    status: 'SUCCESS',
    latencyMs: 98,
  },
  {
    id: 'evt-1004',
    timestamp: '3 mins ago',
    service: 'Amazon DynamoDB',
    action: 'PutItem (CivicFixReports)',
    details: 'Indexed REP-9042 with GSI StatusIndex and DepartmentIndex',
    status: 'SUCCESS',
    latencyMs: 22,
  },
  {
    id: 'evt-1005',
    timestamp: '4 mins ago',
    service: 'Amazon EventBridge',
    action: 'PutEvents (civic.events)',
    details: 'Dispatched event "CivicFix.ReportCreated" with high severity payload',
    status: 'SUCCESS',
    latencyMs: 46,
  },
  {
    id: 'evt-1006',
    timestamp: '5 mins ago',
    service: 'AWS Step Functions',
    action: 'StartExecution (CivicFixResolutionFlow)',
    details: 'Resolution state machine initialized. Execution ARN: arn:aws:states:...:9042-exec',
    status: 'SUCCESS',
    latencyMs: 110,
  },
];

export const SAMPLE_STEP_FUNCTION_EXECUTION: StepFunctionExecution = {
  executionArn: 'arn:aws:states:us-east-1:123456789012:execution:CivicFixResolutionFlow:9042-exec',
  reportId: 'REP-9042',
  status: 'RUNNING',
  startedAt: '2026-09-07T18:32:00Z',
  steps: [
    {
      id: 'step-1',
      name: 'Citizen Report Ingestion',
      service: 'Amazon API Gateway',
      status: 'COMPLETED',
      durationMs: 84,
      timestamp: '18:32:00',
      details: 'Payload validated against JSON schema and rate-limit checked.',
    },
    {
      id: 'step-2',
      name: 'Secure Evidence Archival',
      service: 'Amazon S3',
      status: 'COMPLETED',
      durationMs: 145,
      timestamp: '18:32:01',
      details: 'Uploaded to S3 bucket with client-side SHA-256 fingerprint verification.',
    },
    {
      id: 'step-3',
      name: 'Multimodal Bedrock Analysis',
      service: 'Amazon Bedrock',
      status: 'COMPLETED',
      durationMs: 842,
      timestamp: '18:32:02',
      details: 'Claude 3.5 Sonnet extracted objects, calculated severity (94), and generated remediation plan.',
    },
    {
      id: 'step-4',
      name: 'Vector Duplicate Identification',
      service: 'Amazon OpenSearch',
      status: 'COMPLETED',
      durationMs: 98,
      timestamp: '18:32:03',
      details: '1536-dim Titan vector compared. Top similarity 8.4% (Threshold: 75%). Classified as UNIQUE.',
    },
    {
      id: 'step-5',
      name: 'Triage & Priority Gate',
      service: 'AWS Lambda',
      status: 'COMPLETED',
      durationMs: 34,
      timestamp: '18:32:03',
      details: 'Severity score 94 >= 85 triggered CRITICAL classification branch.',
    },
    {
      id: 'step-6',
      name: 'Department Dispatch & Queue',
      service: 'Amazon DynamoDB',
      status: 'COMPLETED',
      durationMs: 42,
      timestamp: '18:32:04',
      details: 'Assigned to Road Maintenance & Infrastructure queue with high-priority SLA (2h).',
    },
    {
      id: 'step-7',
      name: 'Event Broadcast & Notification',
      service: 'Amazon EventBridge',
      status: 'COMPLETED',
      durationMs: 51,
      timestamp: '18:32:04',
      details: 'Broadcasted CivicFix.CriticalAlert to city emergency operations center.',
    },
    {
      id: 'step-8',
      name: 'Work Order Execution & Verification',
      service: 'AWS Step Functions',
      status: 'RUNNING',
      durationMs: 18000,
      timestamp: '18:32:05',
      details: 'Crew en route. Awaiting post-repair photo verification trigger.',
    },
  ],
};
